name: Teotihuacan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.591303801862523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2756769449915737
  lightness: 0.4077388378791511
  saturation: 0.4495913153514266
  rhythmicContrast: 0.1290252599865198
purpose: []
